### ISSUE TITLE
Random people in the wrong spot (equator)

### ISSUE THREAD

**Issue by david476** [david476/d.tech-Alumni#5]
:(

**Comment by bertturtle** [comment]
It if the name of their college has a comma in it

**Comment by bertturtle** [comment]
It will mess with the csv

**Comment by david476** [comment]
Gotcha, I'll try putting your CSV parser back in.

**Comment by david476** [comment]
It looks like Cole's just doesn't deal with quoted strings.

**Comment by david476** [comment]
Fixed as of f23eac0746e7f2023a25b2a582ea843e88a05ed8
